server:
  port: 9400

spring:
  application:
    name: scts-tms
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scts-tms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jiahao81
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto