server:
  port: 9200

spring:
  application:
    name: scts-ums
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scts-ums?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jiahao81
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

init-user:
  role: 3
