server:
  port: 9000

spring:
  application:
    name: scts-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedOrigins: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: scts-auth
          uri: lb://scts-auth
          predicates:
            - Path=/scts-auth/**
          # StripPrefix过滤器是去掉一个路径。
          filters:
            - StripPrefix=1
        - id: scts-ums
          uri: lb://scts-ums
          predicates:
            - Path=/scts-ums/**
          # StripPrefix过滤器是去掉一个路径。
          filters:
            - StripPrefix=1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
